### ISSUE TITLE
Include example copy to be used when creating a Twitter app

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#100]
**Is your enhancement related to a problem? Please describe.**
As part of the Twitter app setup process, you have to provide an `Application description` (between 10 and 200 characters) and `Tell us how this app will be used` (minimum 100 characters).  We could provide a generic response for each of those that people could copy from the Autoshare for Twitter setup flow into the Twitter app creation screens and help increase the chance that someone successfully sets up the Twitter app and thus the plugin.

**Describe the solution you'd like**

- [ ] draft copy for `Application description`
- [ ] draft copy for `Tell us how this app will be used`
- [ ] include easy copy function for each within the Autoshare for Twitter setup flow
**Designs**

**Describe alternatives you've considered**

keep as-is

**Additional context**

Props to @hearvox for the idea behind this issue.

**Comment by kopepasah** [comment]
@jeffpaul just an FYI, seems that twitter is removing Consumer Keys soon. 

<img width="1275" alt="Screen Shot 2021-01-02 at 4 50 24 PM" src="https://user-images.githubusercontent.com/911283/103468026-bff62480-4d1a-11eb-9952-75a780702498.png">

Which makes the third step obsolete.

<img width="847" alt="Screen Shot 2021-01-02 at 4 51 03 PM" src="https://user-images.githubusercontent.com/911283/103468028-c1275180-4d1a-11eb-9bfd-ace500cf2aa4.png">

Also, the minimum characters are now 200 (not 100) for the app use information.

Happy to help with this content and even a tutorial video that may assist others in setting up this application.

**Comment by jeffpaul** [comment]
@kopepasah so there's no auth step any more with the Twitter app that gets created or is there something new in place of the key/token pair?

**Comment by kopepasah** [comment]
> @kopepasah so there's no auth step any more with the Twitter app that gets created or is there something new in place of the key/token pair?

I am unsure, but I would guess that they are switching to allowing you to only view the keys once, upon creation. The keys will still exist, but will not be viewable in any section (which is what the directions state).

**Comment by jeffpaul** [comment]
Noting we may want to expand this to migrating to the Twitter v2 API:
https://developer.twitter.com/en/docs/twitter-api/migrate
https://developer.twitter.com/en/docs/twitter-api/early-access

and whether any of those additional API features are worth rolling into the plugin in some way.

**Comment by iamdharmesh** [comment]
@jeffpaul I have checked on Twitter v2 API. Currently, we are on v1.1 and using 2 API endpoints
1. Publish Tweet ([POST statuses/update](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update))
2. Upload media (for upload featured image)

Upload media API is not added to V2 yet. So, We have to keep using v1.1 until we get the [replacement of media upload functionality](https://trello.com/c/Zr9zDrJx/109-replacement-of-media-uploads-functionality) in the Twitter v2 API.
![image](https://user-images.githubusercontent.com/10613171/159242627-d470788b-9142-4f61-ae6e-a1fded55873a.png)


Few other things to notice:
1. Older App key and credentials will not work with v2.
2. App is created under project now and by default, the project is getting created with `Essential` access, which only supports V2 APIs. So, users have to Apply for `Elevated` Access in the project in order to make credentials work for v1.1 as well. which means our plugin will work only with an app that is created in the `Elevated` Access project.

**Comment by jeffpaul** [comment]
@iamdharmesh so it sounds like we need to update the setup instructions/docs/settings flow to call out the need for the `Elevated` Access project for new Twitter API accounts correct?  I agree that otherwise it sounds like we need to wait on v2 until it supports Media and then can do a larger up on the setup instructions/docs/settings flow.

**Comment by iamdharmesh** [comment]
> @iamdharmesh so it sounds like we need to update the setup instructions/docs/settings flow to call out the need for the Elevated Access project for new Twitter API accounts correct? 

Yes @jeffpaul. I have drafted PR with updated setup instructions and example copy to get it validated before merging. Can you please help to validate or assign someone who can help with this?
