### ISSUE TITLE
Post Transition and Twitterbot Scraping Timing

### ISSUE THREAD

**Issue by rickalee** [10up/autoshare-for-twitter#112]
Hi team,

We have run into issues on a client project where the Twitter card/Twitterbot does not fetch the featured image. VIPs diagnosis is that our transition_post_status hook is firing too early before all the appropriate Yoast meta can be set. 

Here is the report from VIP team:

"I looked at the php error logs and origin & load balancer request logs for timeframes around some of the items that were published.

This for example is the logging that was already in place for this story: https://twitter.com/9to5toys/status/1337072730714337280

    Dec 10, 2020 @ 16:32:29.000 [10-Dec-2020 16:32:29 UTC] VIPDEBUG: post transition from draft to publish POST: 649991 post_date: 2020-12-10 11:32:29  Container #106864   
    Dec 10, 2020 @ 16:32:35.000 [10-Dec-2020 16:32:35 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #111775   
    Dec 10, 2020 @ 16:32:43.000 [10-Dec-2020 16:32:43 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #68362    
    Dec 10, 2020 @ 16:32:49.000 [10-Dec-2020 16:32:49 UTC] VIPDEBUG: post transition from publish to publish POST: 649991 post_date: 2020-12-10 11:32:29    Container #81683    
The subsequent-to-publish changes (which happen on different origin web containers) seem to occur from these POST requests: /wp-json/wp/v2/posts/649991?_locale=user

It's unclear what those changes are. Even outside of the AJAX/REST requests, we know that many things do hook on the same post transition and can make additional changes to the post content or its metadata.

LB logs show Twitterbot requested the URL at Dec 10, 2020 @ 16:32:35.000 which is in the middle of those changes. And then the next Twitterbot request was at Dec 10, 2020 @ 16:34:10.000 (2 requests) and then the next an hour later.

I think one possibly way to try to deal with possible race conditions (where a post transitioned to published but all the metadata hadn't updated yet and Twitter is fetching possibly older data, or is requesting an image URL that for some reason later changes) would be to either give the tweet action hook a much later priority, or move the actual tweet action to a cron event that is scheduled "immediately" when the post transitions to published."

**Comment by jeffpaul** [comment]
Thanks for the details @rickalee, let's look at adjusting the priority.

**Comment by jeffpaul** [comment]
Looks like changing `10` here may cover this: https://github.com/10up/autoshare-for-twitter/blob/5bed0b820b70c03156836c5fa02b3f30c00d5c7f/includes/admin/post-transition.php#L23

**Comment by jeffpaul** [comment]
@rickalee in trying to chase down more details from your example, it looks like you're referencing this post:
https://9to5toys.com/2020/12/10/google-pixel-4a-5g/
...which appears to have a correct-looking tweet:
https://twitter.com/9to5toys/status/1337072730714337280
...though I'm guessing maybe the bad-looking tweet was deleted and corrected as I see the previous tweet looks off:
https://twitter.com/9to5toys/status/1337070882850828289
...and sharing the post from that tweet:
https://9to5toys.com/2020/12/14/instant-pot-holiday-deals/
...now leads to an image in the Twitter card as expected.

After more testing to determine where things could be going sideways, the assumption from @dinhtungdu and I is that you have the `Image setting` of `Always add the featured image to tweets` disabled as otherwise Autoshare should be sending an image to Twitter without issue.  So our assumption is you have that setting disabled and the issue is more that when Twitter attempts to build its content display (title, excerpt, URL, image) there's a breakdown in a relevant/correct image being available on the site to pull for that display.  Does that sound correct?
