### ISSUE TITLE
The Access Token and Access Token Fields missing in the connection setup.

### ISSUE THREAD

**Issue by LMStudioArt** [10up/autoshare-for-twitter#259]
### Describe your question

I got as far as "Copy the Access Token and Access Token Secret values and paste them below." There are no fields showing for me to paste these into.

![Screen Shot 2023-07-24 at 3 54 55 PM](https://github.com/10up/autoshare-for-twitter/assets/41243431/d4c1c618-031a-4981-ae93-fe51d4f5ad86)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @LMStudioArt,

Thank you for reporting this issue!

Yes, earlier we had 4 fields of Twitter connection settings. However, in the recent release (2.1.0), we have added support for multiple Twitter account connections, reducing the settings to only 2 fields, with other aspects being handled through the Twitter account connection UI. Unfortunately, we missed removing these last 2 lines of setup instructions. Could you please ignore them and proceed by clicking on "Save changes"?

We have already removed the unnecessary lines and fixed the instructions in PR #255, which will be included in the next release.

We appreciate your feedback. Since this issue has already been addressed, I will close this issue. If you encounter any other issues, please feel free to open a new one.

Thanks!
