### ISSUE TITLE
Finding Tweeted posts

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#56]
**Is your enhancement related to a problem? Please describe.**
Faster identification of posts which need Tweeting.  Supporting multi-editor workflow:
* Placement and persistence of Tweet message to support multi editor workflow
* Configurable representation of Tweet status in Post listing
* Configurable Tweet status filter

**Describe the solution you'd like**
Update the All Posts screen to:
- [ ] add filters for "Tweeted" and/or "Not Tweeted"
- [ ] add column for Tweeted status
- [ ] add hover state for rows in Tweeted status column to show the Tweet date(s) and time(s) in a simple title attribute

**Designs**
![Screen Shot 2019-12-13 at 7 20 16 PM](https://user-images.githubusercontent.com/2818133/70841155-a3204380-1ddd-11ea-8be2-20ca16c49e6d.png)

**Describe alternatives you've considered**
n/a

**Additional context**
 Props to @linawiezkowiak and @oszkarnagy for the UX/Design work.

**Comment by kopepasah** [comment]
I spoke with @jeffpaul and I will take on this feature. It is my understanding that no work has been done on this feature, so I may have some back and forth questions after initial investigation. I have some time allotted on Sunday for investigation.

**Comment by thrijith** [comment]
Hi @jeffpaul I've started to look into it, will open up a draft with following points completed.

- [x] add column for Tweeted status
- [x] add hover state for rows in Tweeted status column to show the Tweet date(s) and time(s) in a simple title attribute

I am doubtful about this one as those columns are for post status filters, since we are storing the value of tweet status in post meta not exactly sure how to proceed on this specific one.

- [ ] add filters for "Tweeted" and/or "Not Tweeted"

**Comment by thrijith** [comment]
Hi @jeffpaul - I am still not seeing an option to do the filtering as shown in screenshot above, as it would require to register a custom post status and moving the tweeted posts to new status instead of `publish`, please do correct if I missed something.

Other option to filter that I can see is to add custom filter here, please let me know your thoughts on the same, thanks!

![Screenshot 2021-02-05 at 2 49 27 AM](https://user-images.githubusercontent.com/13589980/106956567-c6821c80-675c-11eb-9537-abd9b4daf23a.png)

**Comment by jeffpaul** [comment]
@thrijith if the Twitter column is sortable, then that probably suffices for this overall issue.

**Comment by thrijith** [comment]
@jeffpaul We can sort if the meta value had just status for the tweet publish, since we have other data in the meta, not sure how sorting would work here. Tried to do it but it hides all the other posts that don't have a tweet status.

**Comment by jeffpaul** [comment]
@thrijith what about whether the meta has a value or not?

**Comment by thrijith** [comment]
Tried with checking existence of meta value but it filters and displays the posts which have the meta on sorting.

**Comment by jeffpaul** [comment]
@thrijith ok, let's consider this sufficiently _done_ and if we get community request for the ability to filter/sort we can re-investigate how to handle.
