### ISSUE TITLE
Tweeting workflow

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#59]
**Is your enhancement related to a problem? Please describe.**
Better system feedback for admins and more clarity on what will happen to reduce "surprises" and increase trust.

**Describe the solution you'd like**
- [x] Own standard slotfill, with default icon
- [ ] ~~If Tweeting is disabled, show but disable controls~~
- [x] Include featured image if specified
- [x] Label updates when enabled to say what it will do
- [x] Icon changes active state too, so that status can be seen (and read too) even if the slotfill is closed
- [ ] ~~Full Tweet message is always shown - enabling different editors to edit the message before (or after) publishing~~
- [x] Short warning when message getting long
- [x] Error when message is too long
- [x] Set max character for the text area, so that people can't enter longer Tweets
- [ ] ~~If there is a featured image specified show the same thumbnail as the "Featured Image" area~~
- [x] Remove featured image from Tweet
- [x] If featured image was removed but still exists - it can be enabled again
- [ ] ~~Show current featured image with 10% opacity underneath to know what the featured image is~~
- [x] State what the action will be, and use appropriate icon colour coding
- [ ] ~~Message controls available in open state~~
- [x] Disabled state copy and icon updated
- [x] Tweeted status shows date/time and link to the Tweet
- [x] A post can be Tweeted multiple times after publishing - even by a different editor
- [x] Post publishing state and icon set appropriately
- [x] Tweet now will expose controls and allow instant Tweeting
- [x] Message and settings should persist to allow multi-editor or dedicated social media person workflow
- [x] If a post has been Tweeted multiple times, the Tweet entries will stack
- [x] Edge-ish case when Post has been switched back to Draft from Published, and has already been Tweeted

**Designs**
DRAFT STATE
Default state: 
![Screen Shot 2019-12-18 at 10 28 23 PM](https://user-images.githubusercontent.com/2818133/71145058-c1bf7980-21e5-11ea-80d5-6ddba40184a7.png)

Disabled state: 
![Screen Shot 2019-12-18 at 10 29 03 PM](https://user-images.githubusercontent.com/2818133/71145073-d439b300-21e5-11ea-8472-9d8908e02f66.png)

Disabled state with featured image: 
![Screen Shot 2019-12-18 at 10 29 32 PM](https://user-images.githubusercontent.com/2818133/71145087-e582bf80-21e5-11ea-97a3-06916fd24a35.png)

Enabled state: 
![Screen Shot 2019-12-18 at 10 30 03 PM](https://user-images.githubusercontent.com/2818133/71145100-f6cbcc00-21e5-11ea-8349-023e64dc78f1.png)

Enabled - length warning: 
![Screen Shot 2019-12-18 at 10 30 30 PM](https://user-images.githubusercontent.com/2818133/71145120-05b27e80-21e6-11ea-9dfc-41edeeb32705.png)

Enabled - length error: 
![Screen Shot 2019-12-18 at 10 30 58 PM](https://user-images.githubusercontent.com/2818133/71145138-182cb800-21e6-11ea-9143-045ac3baf8d8.png)

Enabled - with featured image: 
![Screen Shot 2019-12-18 at 10 31 27 PM](https://user-images.githubusercontent.com/2818133/71145158-28dd2e00-21e6-11ea-94fa-58916f6de27d.png)

Enabled - featured image removed: 
![Screen Shot 2019-12-18 at 10 31 55 PM](https://user-images.githubusercontent.com/2818133/71145175-385c7700-21e6-11ea-97b1-0ccfa5243d67.png)

PRE-PUBLISH CHECKS
Pre-publish - Enabled: 
![Screen Shot 2019-12-18 at 10 32 22 PM](https://user-images.githubusercontent.com/2818133/71145189-4a3e1a00-21e6-11ea-8e34-597ab45d0644.png)

Pre-publish - Enabled & Open: 
![Screen Shot 2019-12-18 at 10 32 53 PM](https://user-images.githubusercontent.com/2818133/71145202-5c1fbd00-21e6-11ea-8fdd-63f95fb3443a.png)

Pre-publish - Disabled: 
![Screen Shot 2019-12-18 at 10 33 21 PM](https://user-images.githubusercontent.com/2818133/71145217-6e016000-21e6-11ea-8036-c3f5c9862fe2.png)

PUBLISHED
Published - Tweeted: 
![Screen Shot 2019-12-18 at 10 33 48 PM](https://user-images.githubusercontent.com/2818133/71145232-7ce81280-21e6-11ea-8df7-1ded50217a69.png)

Published - Disabled: 
![Screen Shot 2019-12-18 at 10 34 10 PM](https://user-images.githubusercontent.com/2818133/71145244-8a050180-21e6-11ea-959e-010a367c2a84.png)

Published - Tweet now: 
![Screen Shot 2019-12-18 at 10 34 35 PM](https://user-images.githubusercontent.com/2818133/71145256-98531d80-21e6-11ea-863f-0fbfddd6054d.png)

Published - Tweeted multiple times: 
![Screen Shot 2019-12-18 at 10 34 58 PM](https://user-images.githubusercontent.com/2818133/71145275-a6a13980-21e6-11ea-9161-d57b14abebc0.png)

DRAFT & TWEETED
Draft (after being Published): 
![Screen Shot 2019-12-18 at 10 35 25 PM](https://user-images.githubusercontent.com/2818133/71145296-b587ec00-21e6-11ea-9b5c-4c5c5ef4fda8.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Props to @linawiezkowiak and @oszkarnagy for the UX/Design work.

**Comment by kopepasah** [comment]
Yeah, I really had a hay-day trying to find where to edit the tweet before publishing... and even started debugging to see if there were issues created by 5.6. 🤣

Rather than adding this as a document panel, it could also exist as a plugin Sidebar (much like Yoast) that a user can get to with a few quick clicks (or even set as a favorite, if it is used a lot).

REF: https://developer.wordpress.org/block-editor/developers/slotfills/plugin-sidebar/

**Comment by Sidsector9** [comment]
@jeffpaul Can this issue be further broken down so that PRs raised are smaller? I would like to pick this up.

**Comment by jeffpaul** [comment]
@Sidsector9 yes, should certainly be handled in various PRs based on sub-set of the overall checklist of items in the issue description.  Let me know if you have a sub-set of items in mind or would like me to look at breaking the larger checklist into groups.

**Comment by iamdharmesh** [comment]
@jeffpaul @Sidsector9 I think we can break this into these smaller tasks. Please let me know your thoughts on this, if looks good to you. I will create issue for each.

**1. Add AutoTweet panel (Slotfill) for enable/disable tweet on publish and add colour-coded icons Pre-Publish Panel title** (#176)
- [x] Own standard slotfill, with default icon
- [ ] ~~If Tweeting is disabled, show but disable controls~~
- [x] Label updates when enabled to say what it will do
- [x] Icon changes active state too, so that status can be seen (and read too) even if the slotfill is closed
- [x] State what the action will be, and use appropriate icon colour coding
- [ ] ~~Message controls available in open state~~
- [x] Disabled state copy and icon updated

**2. Improve edit Tweet message.** (#178)
 - [ ] ~~Full Tweet message is always shown - enabling different editors to edit the message before (or after) publishing~~
 - [x] Short warning when message getting long
 - [x] Error when message is too long
 - [x] Set max character for the text area, so that people can't enter longer Tweets

**3. Add functionality for add/remove featured image from tweet** (#179)
- [x] Include featured image if specified
- [ ] ~~If there is a featured image specified show the same thumbnail as the "Featured Image" area~~
- [x] Remove featured image from Tweet
- [ ] ~~If featured image was removed but still exists - it can be enabled again~~
- [ ] ~~Show current featured image with 10% opacity underneath to know what the featured image is~~

**4. [Post-Publish Panel] Tweet status improvements** (#180)
- [x] Tweeted status shows date/time and link to the Tweet
- [x] Post publishing state and icon set appropriately
- [x] If a post has been Tweeted multiple times, the Tweet entries will stack

**5. [Post-Publish Panel]  Add "Tweet now" functionality.** (#181)
- [x] A post can be Tweeted multiple times after publishing - even by a different editor
- [x] Tweet now will expose controls and allow instant Tweeting
- [x] Message and settings should persist to allow multi-editor or dedicated social media person workflow

**6. Handle re-tweet in case of post has been switched back to Draft from Published, and has already been Tweeted** (#182)
- [x] Edge-ish case when Post has been switched back to Draft from Published, and has already been Tweeted

Thanks.

**Comment by Sidsector9** [comment]
Looks good to me @iamdharmesh, nice work! 👍

**Comment by iamdharmesh** [comment]
Issue completed by various subtasks.
